### ISSUE TITLE
Exporter Error Out after ~8 hours 

### ISSUE THREAD

**Issue by afreels95** [wywywywy/tesla-prometheus-exporter#12]
The exporter was working fine for a few hours then I started exiting in a loop with this error. 

Cannot read property '0' of undefined TypeError: Cannot read property '0' of undefined
    at /app/tesla-prometheus-exporter.js:361:95
    at Generator.next (<anonymous>)
    at fulfilled (/app/tesla-prometheus-exporter.js:25:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

Running in Docker config below
tesla-exporter:
       container_name: tesla-exporter
       image: wywywywy/tesla_exporter
       ports:
           - '9885:9885'
       environment:
           - TESLA_EXPORTER_RETRIES=0
           - TESLA_EXPORTER_TOKEN=<token>

**Comment by wywywywy** [comment]
My apologies. I didn't see your issue until now.

I'm working on a version 2 now and hopefully it'll sort out the issue you're having.

**Comment by wywywywy** [comment]
Okay `v2.0.0` has been released.  Can you please give it a try and see if it works for you?

Also I recommend leaving `TESLA_EXPORTER_RETRIES` as default, because the Tesla API itself sometimes errors out randomly.

**Comment by wywywywy** [comment]
@afreels95 Token now refreshes every 7 hours in `v2.0.1`. So it shouldn't error out after 8 hours any more. Please can you give it a test.
