### ISSUE TITLE
Exception on startup: `Cannot read property 'find' of null`

### ISSUE THREAD

**Issue by radeklat** [wywywywy/tesla-prometheus-exporter#16]
Hello @wywywywy :wave: 

I tried to use the the tesla-prometheus-exporter docker image, but sadly it fail on startup with the following error:

```
{
2024-03-01T15:40:07.478966066Z   _: [],
2024-03-01T15:40:07.478970493Z   token: '<REFRESH TOKEN>',
2024-03-01T15:40:07.478976488Z   t: '<REFRESH TOKEN>',
2024-03-01T15:40:07.478981263Z   port: 9885,
2024-03-01T15:40:07.478983669Z   p: 9885,
2024-03-01T15:40:07.478985937Z   interval: 120,
2024-03-01T15:40:07.478988175Z   i: 120,
2024-03-01T15:40:07.478990373Z   vin: '<VIN>',
2024-03-01T15:40:07.478992635Z   retries: 3,
2024-03-01T15:40:07.478994852Z   debug: true,
2024-03-01T15:40:07.478997095Z   d: true,
2024-03-01T15:40:07.478999341Z   '$0': 'tesla-prometheus-exporter.js'
2024-03-01T15:40:07.479001623Z }
2024-03-01T15:40:07.481181215Z Exporter listening on port 9885... (press CTRL+c to interrupt)
2024-03-01T15:40:07.481245848Z Requesting access token from Tesla...
2024-03-01T15:40:08.056881487Z Unexpected error. Exiting...
2024-03-01T15:40:08.056913593Z Cannot read property 'find' of null TypeError: Cannot read property 'find' of null
2024-03-01T15:40:08.056919994Z     at /app/tesla-prometheus-exporter.js:367:52
2024-03-01T15:40:08.056921364Z     at Generator.next (<anonymous>)
2024-03-01T15:40:08.056922786Z     at fulfilled (/app/tesla-prometheus-exporter.js:29:58)
2024-03-01T15:40:08.056924129Z     at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

I'm using version 2.0.1 of the image. I'm assuming the error is cause by no cars returned by the API?

**Comment by wywywywy** [comment]
Yes it does sound like Tesla thinks that there isn't any cars in your account.

Do you know of another API endpoint that we can associated but not owned cars?

**Comment by radeklat** [comment]
I don't :( I'm actually completely new to the Tesla API. But getting the refresh token according to the instructions did show the correct car as well.
